apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stalwart-system

resources:
- namespace.yaml
- deployment.yaml
- pvc.yaml
- svc.yaml
- httproute.yaml

configMapGenerator:
- name: stalwart-config
  files:
    - config.toml