apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      initContainers:
      - name: copy-zones
        image: busybox
        command: ["sh", "-c", "cp /tmp/zones/db.* /var/lib/bind/ && chown -R 100:101 /var/lib/bind && chmod -R 775 /var/lib/bind"]
        volumeMounts:
        - name: zone-templates
          mountPath: /tmp/zones
        - name: bind9-data
          mountPath: /var/lib/bind
      containers:
      - name: bind9
        image: internetsystemsconsortium/bind9:9.21
        args: ["-4", "-f", "-c", "/etc/bind/named.conf", "-g"]
        ports:
        - containerPort: 53
          name: dns-udp
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 953
          name: rndc
          protocol: TCP
        volumeMounts:
        - name: bind9-config
          mountPath: /etc/bind/named.conf
          subPath: named.conf
        - name: bind9-zones
          mountPath: /var/lib/bind
      volumes:
      - name: bind9-config
        configMap:
          name: bind9-config
      - name: zone-templates
        configMap:
          name: bind9-zones
      - name: bind9-data
        persistentVolumeClaim:
          claimName: bind9-data-pvc