apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- pvc.yaml
- svc.yaml


configMapGenerator:
- name: bind9-config
  files:
    - named.conf
- name: bind9-zones
  files:
    - zones/db.org1.com
    - zones/db.org2.com