apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml

patches:
- path: delete-namespace-patch.yaml
  target:
    kind: Namespace
    name: argocd-image-updater-system
    
namespace: argocd
