apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml

helmCharts:
  - name: trust-manager
    repo: https://charts.jetstack.io
    version: v0.20.3
    releaseName: trust-manager
    namespace: cert-manager
    valuesFile: values.yaml

patches:
  - target:
      kind: Namespace
      name: cert-manager
    patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager
      $patch: delete