apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- lab-ca-distribution.yaml

helmCharts:
  - name: trust-manager
    repo: https://charts.jetstack.io
    version: v0.20.3
    releaseName: trust-manager
    namespace: cert-manager
    valuesFile: values.yaml
