apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- secret.yaml

secretGenerator:
- name: tunnel-token
  files: [secret.yaml]
  options:
    annotations:
      config.kubernetes.io/local-config: "true"

namespace: cloudflare-tunnel

configurations:
- nameReference.yaml