apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- install.yaml
- projects.yaml
- image-updater

patches:
- path: enable-helm-redndering.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
- path: enable-http.yaml
  target:
    kind: ConfigMap
    name: argocd-cmd-params-cm

namespace: argocd
