apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- kgateway-app.yaml
- argocd-app.yaml
- sealed-secrets-app.yaml
- cnpg-app.yaml
- crossplane-app.yaml
- keycloak-app.yaml
- externaldns-app.yaml
- bind9-app.yaml
- stalwart-app.yaml
- snappymail-app.yaml
- staticDNS-app.yaml
- certmanager-app.yaml
- trustmanager-app.yaml
