apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- namespace.yaml
- secret.yaml

helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns/
    version: 1.20.0
    releaseName: external-dns
    namespace: externaldns-system
    valuesFile: values.yaml
    includeCRDs: true

namespace: externaldns-system